--- 
format: 1
handler: 
  commit: 9e4a91705d235814629b3cf744ea929fd8ac972c
  branch: master
lock: false
repository_class: Piston::Git::Repository
repository_url: git@github.com:topfunky/PeepOpen-EditorSupport.git
