--- 
format: 1
handler: 
  commit: de0edf851b8aee8c66302bdf6d5d61099df4d834
  branch: master
lock: false
repository_class: Piston::Git::Repository
repository_url: git@github.com:topfunky/PeepOpen-EditorSupport.git
